name: edgexchange

x-env: &env
  env_file: .env

x-cache: &cache
  restart: always
  build: ./system/cache

services:
  livecache:
    <<: [*cache, *env]
    ports: ["${LCPORT}:6379"]
    command: ["--save", ""]

  sessioncache:
    <<: [*cache, *env]
    volumes:
      - sessiondata:/data
    ports: ["${SCPORT}:6379"]
    command: ["--appendonly", "yes"]

  database:
    <<: *env
    restart: always
    build: ./system/database
    volumes:
      - systemdata:/data
    ports: ["${DBPORT}:5432"]

  backend:
    <<: *env
    restart: on-failure
    build: ./system/application/backend
    ports: ["${BEPORT}:8000"]
    depends_on:
      database: { condition: service_healthy }
      livecache: { condition: service_healthy }
      sessioncache: { condition: service_healthy }

  frontend:
    <<: *env
    restart: always
    build: ./system/application/frontend
    volumes:
      - ./system/application/frontend:/frontend
      - /frontend/node_modules
      - /frontend/.next
    ports: ["${FEPORT}:3000"]
    depends_on:
      backend: { condition: service_healthy }

volumes:
  systemdata:
  sessiondata: